apiVersion: v1
kind: Service
metadata:
  name: final-api-lb
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer
  ports:
    - name: {{ .Values.load_balancer.port_name }}
      port: {{ .Values.load_balancer.port }}
      targetPort: {{ .Values.load_balancer.targetPort }}
      protocol: {{ .Values.load_balancer.protocol }}
  selector:
    app: {{ .Values.deployment.name }}
